import { Link } from "react-router-dom";
import { ArrowUpRight, BriefcaseBusiness, Clock3, FolderKanban, Plus, Sparkles, TrendingUp, UsersRound } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useAuth } from "@/components/auth-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { api } from "@/lib/api";
import { formatDate, formatMoney } from "@/lib/utils";
import { useTranslation } from "react-i18next";

export function DashboardPage() {
  const { user } = useAuth();
  const { t } = useTranslation();
  const { data, isLoading } = useQuery({ queryKey: ["jobs", "dashboard"], queryFn: () => api.getJobs({ limit: 5 }) });
  const { data: projects = [] } = useQuery({ queryKey: ["projects"], queryFn: api.getProjects });
  const { data: proposals = [] } = useQuery({ queryKey: ["proposals", user?.role === "CLIENT" ? "received" : "mine"], queryFn: user?.role === "CLIENT" ? api.getReceivedProposals : api.getMyProposals });
  const isClient = user?.role === "CLIENT";
  const name = user?.profile?.name?.split(" ")[0] ?? "there";

  return <div className="space-y-8"><section className="relative overflow-hidden rounded-3xl border border-border/80 bg-card px-6 py-8 sm:px-10 sm:py-10"><div className="absolute -right-20 -top-28 h-72 w-72 rounded-full bg-primary/15 blur-3xl" /><div className="relative flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="mb-4 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-primary"><Sparkles className="h-3.5 w-3.5" />{t("dashboard.workspace")}</div><h1 className="max-w-xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{t("dashboard.goodMorning", { name })}</h1><p className="mt-3 max-w-lg text-sm leading-6 text-muted-foreground">{isClient ? t("dashboard.clientIntro") : t("dashboard.freelancerIntro")}</p></div><Link to={isClient ? "/jobs/new" : "/jobs"}><Button size="lg">{isClient ? <><Plus className="h-4 w-4" />{t("common.postProject")}</> : <><CompassIcon /><span>{t("dashboard.exploreJobs")}</span></>}</Button></Link></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={BriefcaseBusiness} label={isClient ? t("dashboard.proposalRequests") : t("dashboard.proposalsSent")} value={String(proposals.length)} hint={proposals.length ? t("dashboard.keepMoving") : t("dashboard.readyFirst")} /><StatCard icon={FolderKanban} label={t("dashboard.activeProjects")} value={String(projects.filter((project) => project.status !== "COMPLETED" && project.status !== "CANCELLED").length)} hint={projects.length ? t("dashboard.openWorkspace") : t("dashboard.nothingProgress")} /><StatCard icon={TrendingUp} label={t("dashboard.completedProjects")} value={String(projects.filter((project) => project.status === "COMPLETED").length)} hint={t("dashboard.buildTrackRecord")} /><StatCard icon={Clock3} label={t("dashboard.responseTime")} value="—" hint={t("dashboard.keepMoving")} /></section>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{isClient ? t("dashboard.freshTalent") : t("dashboard.projectsWorth")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.marketplaceSelection")}</p></div><Link to="/jobs" className="text-sm font-semibold text-primary hover:underline">{t("dashboard.viewAll")}</Link></CardHeader><CardContent className="space-y-3">{isLoading ? <LoadingRows /> : data?.items.length ? data.items.map((job) => <JobRow key={job.id} job={job} />) : <EmptyJobs isClient={isClient} />}</CardContent></Card><Card className="overflow-hidden"><CardHeader><CardTitle>{t("dashboard.profileHarder")}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{t("dashboard.profileDescription")}</p></CardHeader><CardContent><div className="mb-5 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full w-[35%] rounded-full bg-primary" /></div><div className="flex items-center justify-between text-xs"><span className="font-semibold">{t("dashboard.profileComplete", { percent: 35 })}</span><span className="text-muted-foreground">{t("dashboard.sectionsComplete", { done: 2, total: 6 })}</span></div><Link to="/profile" className="mt-6 flex items-center justify-between rounded-xl border border-border px-4 py-3 text-sm font-semibold transition hover:border-primary/30 hover:bg-accent">{t("dashboard.completeProfile")} <ArrowUpRight className="h-4 w-4 text-primary" /></Link><div className="mt-4 flex items-start gap-3 rounded-xl bg-primary/[.07] p-4"><UsersRound className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><p className="text-xs leading-5 text-muted-foreground">{t("dashboard.addSkills")}</p></div></CardContent></Card></div>
  </div>;
}

function StatCard({ icon: Icon, label, value, hint }: { icon: typeof BriefcaseBusiness; label: string; value: string; hint: string }) {
  return <Card className="p-5"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></span><ArrowUpRight className="h-4 w-4 text-muted-foreground/50" /></div><div className="mt-5 text-2xl font-semibold tracking-tight">{value}</div><div className="mt-1 text-sm font-medium">{label}</div><div className="mt-1 text-xs text-muted-foreground">{hint}</div></Card>;
}
function JobRow({ job }: { job: import("@/lib/api").Job }) { return <Link to={`/jobs/${job.id}`} className="flex items-center justify-between gap-4 rounded-xl border border-transparent px-3 py-3 transition hover:border-border hover:bg-accent"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-semibold">{job.title}</h3><Badge variant="secondary">{job.category ?? "Open"}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{job.client.profile?.name ?? "Archer client"} · {formatDate(job.deadline)}</p></div><span className="shrink-0 text-sm font-semibold">{formatMoney(job.budgetAmount, job.budgetCurrency)}</span></Link>; }
function LoadingRows() { return <>{[1, 2, 3].map((item) => <div key={item} className="h-16 animate-pulse rounded-xl bg-secondary/70" />)}</>; }
function EmptyJobs({ isClient }: { isClient: boolean }) { const { t } = useTranslation(); return <div className="rounded-2xl border border-dashed border-border px-6 py-10 text-center"><p className="font-semibold">{t("dashboard.nothingHere")}</p><p className="mt-1 text-sm text-muted-foreground">{isClient ? t("dashboard.postToAttract") : t("dashboard.newOpportunities")}</p></div>; }
function CompassIcon() { return <Sparkles className="h-4 w-4" />; }
