import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, BriefcaseBusiness, Clock3, FolderKanban, MessageCircle } from "lucide-react";
import { useAuth } from "@/components/auth-provider";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { api, type Project } from "@/lib/api";
import { formatDate, formatMoney } from "@/lib/utils";
import { useTranslation } from "react-i18next";

export function ProjectsPage() {
  const { user } = useAuth();
  const { t } = useTranslation();
  const { data: projects, isLoading, isError } = useQuery({ queryKey: ["projects"], queryFn: api.getProjects });
  const isClient = user?.role === "CLIENT";
  return <div className="space-y-7"><section><p className="mb-2 text-sm font-semibold text-primary">{t("projects.workspace")}</p><h1 className="text-3xl font-semibold tracking-[-.04em]">{t("projects.title")}<span className="text-primary">.</span></h1><p className="mt-2 text-sm text-muted-foreground">{t("projects.description")}</p></section>{isLoading ? <div className="grid gap-4 lg:grid-cols-2">{[1, 2, 3, 4].map((item) => <div key={item} className="h-56 animate-pulse rounded-2xl bg-secondary/70" />)}</div> : isError ? <Card className="p-10 text-center"><p className="font-semibold">{t("projects.couldNotLoad")}</p><p className="mt-1 text-sm text-muted-foreground">{t("jobs.apiRunning")}</p></Card> : projects?.length ? <div className="grid gap-4 lg:grid-cols-2">{projects.map((project) => <ProjectCard key={project.id} project={project} isClient={isClient} />)}</div> : <Card className="p-12 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><FolderKanban className="h-5 w-5" /></span><p className="mt-4 font-semibold">{t("projects.noProjects")}</p><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-muted-foreground">{isClient ? t("projects.acceptFirst") : t("projects.acceptedByClient")}</p></Card>}</div>;
}

function ProjectCard({ project, isClient }: { project: Project; isClient: boolean }) { const { t } = useTranslation(); const other = isClient ? project.freelancer : project.client; const completed = project.milestones.filter((milestone) => milestone.status === "COMPLETED").length; return <Link to={`/projects/${project.id}`} className="group"><Card className="h-full p-6 transition hover:-translate-y-0.5 hover:border-primary/30"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><BriefcaseBusiness className="h-4 w-4" /></span><div><p className="text-xs text-muted-foreground">{isClient ? t("projects.freelancer") : t("projects.client")}</p><p className="text-sm font-semibold">{other.profile?.name ?? other.email}</p></div></div><Badge className={statusClass(project.status)}>{project.status.replace("_", " ")}</Badge></div><h2 className="mt-6 text-lg font-semibold tracking-tight">{project.job.title}</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-secondary/60 p-3"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-muted-foreground">{t("projects.agreedAmount")}</p><p className="mt-1 text-sm font-semibold">{formatMoney(project.agreedAmount, project.agreedCurrency)}</p></div><div className="rounded-xl bg-secondary/60 p-3"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-muted-foreground">{t("projects.milestones")}</p><p className="mt-1 text-sm font-semibold">{completed}/{project.milestones.length || 0} {t("projects.completed")}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-border/70 pt-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><Clock3 className="h-3.5 w-3.5" />{t("common.due")} {formatDate(project.job.deadline)}</span><span className="inline-flex items-center gap-1.5">{project.conversation?.messages.length ?? 0} {t("common.messages")} <MessageCircle className="h-3.5 w-3.5" /><ArrowUpRight className="ml-2 h-4 w-4 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-primary" /></span></div></Card></Link>; }
function statusClass(status: string) { return status === "COMPLETED" ? "bg-emerald-500/15 text-emerald-400" : status === "CANCELLED" ? "bg-destructive/12 text-destructive" : ""; }
