import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, BriefcaseBusiness, Inbox, Send, UserRound } from "lucide-react";
import { useAuth } from "@/components/auth-provider";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { api, type Proposal } from "@/lib/api";
import { formatDate, formatMoney } from "@/lib/utils";
import { useTranslation } from "react-i18next";

export function ProposalsPage() {
  const { user } = useAuth();
  const { t } = useTranslation();
  const isClient = user?.role === "CLIENT";
  const { data: proposals, isLoading, isError } = useQuery({ queryKey: ["proposals", isClient ? "received" : "mine"], queryFn: isClient ? api.getReceivedProposals : api.getMyProposals });
  return <div className="space-y-7"><section><p className="mb-2 text-sm font-semibold text-primary">{isClient ? t("proposals.hiringInbox") : t("proposals.yourProposals")}</p><h1 className="text-3xl font-semibold tracking-[-.04em]">{isClient ? t("proposals.peopleReady") : t("proposals.keepMoving")}<span className="text-primary">.</span></h1><p className="mt-2 text-sm text-muted-foreground">{isClient ? t("proposals.clientDescription") : t("proposals.freelancerDescription")}</p></section><div className="grid gap-4 sm:grid-cols-3"><SummaryCard icon={isClient ? Inbox : Send} label={isClient ? t("proposals.received") : t("proposals.sent")} value={String(proposals?.length ?? 0)} /><SummaryCard icon={BriefcaseBusiness} label={t("proposals.inReview")} value={String(proposals?.filter((proposal) => proposal.status === "SUBMITTED").length ?? 0)} /><SummaryCard icon={UserRound} label={isClient ? t("proposals.accepted") : t("proposals.won")} value={String(proposals?.filter((proposal) => proposal.status === "ACCEPTED").length ?? 0)} /></div>{isLoading ? <div className="space-y-3">{[1, 2, 3].map((item) => <div key={item} className="h-32 animate-pulse rounded-2xl bg-secondary/70" />)}</div> : isError ? <Card className="p-10 text-center"><p className="font-semibold">{t("proposals.couldNotLoad")}</p><p className="mt-1 text-sm text-muted-foreground">{t("jobs.apiRunning")}</p></Card> : proposals?.length ? <div className="space-y-3">{proposals.map((proposal) => <ProposalRow key={proposal.id} proposal={proposal} isClient={isClient} />)}</div> : <Card className="p-12 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary">{isClient ? <Inbox className="h-5 w-5" /> : <Send className="h-5 w-5" />}</div><p className="mt-4 font-semibold">{isClient ? t("proposals.noProposals") : t("proposals.proposalsAppear")}</p><p className="mx-auto mt-1 max-w-sm text-sm leading-6 text-muted-foreground">{isClient ? t("proposals.receivedDescription") : t("proposals.sentDescription")}</p>{!isClient && <Link to="/jobs" className="mt-5 inline-flex text-sm font-semibold text-primary hover:underline">{t("proposals.exploreMarketplace")} <ArrowUpRight className="ml-1 h-4 w-4" /></Link>}</Card>}</div>;
}

function ProposalRow({ proposal, isClient }: { proposal: Proposal; isClient: boolean }) { const { t } = useTranslation(); const person = isClient ? proposal.freelancer.profile?.name ?? proposal.freelancer.email : proposal.job.client.profile?.name ?? proposal.job.client.email; return <Link to={`/proposals/${proposal.id}`} className="group block"><Card className="p-5 transition hover:border-primary/30 hover:bg-card/95"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge className={statusClass(proposal.status)}>{proposal.status}</Badge><span className="text-xs text-muted-foreground">{formatDate(proposal.createdAt)}</span></div><h2 className="mt-3 truncate text-base font-semibold">{proposal.job.title}</h2><p className="mt-1 text-sm text-muted-foreground">{isClient ? t("proposals.from") : t("proposals.for")} {person}</p></div><div className="flex items-center justify-between gap-6 sm:justify-end"><div className="text-left sm:text-right"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-muted-foreground">{isClient ? t("proposals.proposedAmount") : t("proposals.yourBid")}</p><p className="mt-1 text-base font-semibold">{formatMoney(proposal.bidAmount, proposal.bidCurrency)}</p></div><ArrowUpRight className="h-4 w-4 text-muted-foreground transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-primary" /></div></div></Card></Link>; }
function SummaryCard({ icon: Icon, label, value }: { icon: typeof Inbox; label: string; value: string }) { return <Card className="flex items-center gap-4 p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></span><div><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div></Card>; }
function statusClass(status: string) { return status === "ACCEPTED" ? "bg-emerald-500/15 text-emerald-400" : status === "REJECTED" || status === "WITHDRAWN" ? "bg-destructive/12 text-destructive" : ""; }
