import { Link } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, Text, View } from 'react-native';
import { Button, Card, Field, Notice, Screen, colors, ui } from '@/components/ui';
import { ApiError, type UserRole } from '@/lib/api';
import { useAuth } from '@/providers/auth-provider';

export default function RegisterScreen() {
  const { signUp } = useAuth();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [role, setRole] = useState<UserRole>('FREELANCER'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit() { setError(''); setBusy(true); try { await signUp({ name: name.trim(), email: email.trim(), password, role }); } catch (e) { setError(e instanceof ApiError ? e.message : 'Could not create your account. Please try again.'); } finally { setBusy(false); } }
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: colors.bg }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Screen scroll style={{ flexGrow: 1, justifyContent: 'center', paddingTop: 40, paddingBottom: 40 }}><View style={{ gap: 8, marginBottom: 12 }}><Text style={{ color: colors.purple, fontWeight: '900', fontSize: 17, letterSpacing: 1 }}>archer.</Text><Text style={{ color: colors.text, fontSize: 32, lineHeight: 39, fontWeight: '800', letterSpacing: -0.8 }}>Create your account</Text><Text style={{ color: colors.muted, fontSize: 15, lineHeight: 23 }}>Tell us how you want to get started.</Text></View><Card><Field label="Your name" value={name} onChangeText={setName} autoComplete="name" textContentType="name" placeholder="Your name" /><Field label="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email" placeholder="you@example.com" /><Field label="Password" value={password} onChangeText={setPassword} secureTextEntry autoComplete="new-password" placeholder="At least 8 characters" /></Card><Text style={{ color: colors.text, fontWeight: '700', fontSize: 13 }}>I’m joining as a</Text><View style={{ flexDirection: 'row', gap: 10 }}>{(['FREELANCER', 'CLIENT'] as const).map((item) => <Pressable key={item} onPress={() => setRole(item)} style={{ flex: 1, backgroundColor: role === item ? '#9b8cff1a' : colors.card, borderWidth: 1, borderColor: role === item ? colors.purple : colors.line, padding: 14, borderRadius: 15, gap: 4 }}><Text style={{ color: role === item ? colors.purple : colors.text, fontWeight: '800' }}>{item === 'CLIENT' ? 'Client' : 'Freelancer'}</Text><Text style={ui.small}>{item === 'CLIENT' ? 'I want to hire talent' : 'I want to find work'}</Text></Pressable>)}</View>{error ? <Notice>{error}</Notice> : null}<Button title="Create account" onPress={() => void submit()} loading={busy} disabled={!name || !email || password.length < 8} /><View style={{ flexDirection: 'row', justifyContent: 'center', gap: 5, paddingTop: 5 }}><Text style={{ color: colors.muted }}>Already have an account?</Text><Link href="/(auth)/login" style={{ color: colors.purple, fontWeight: '700' }}>Sign in</Link></View></Screen></KeyboardAvoidingView>;
}
