import type { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps, type ViewProps } from 'react-native';

export const colors = { bg: '#0d111c', card: '#141a28', cardAlt: '#1c2434', line: '#2a3449', text: '#f4f6fb', muted: '#929db2', purple: '#9b8cff', green: '#73ddb4', red: '#ff8a97' };
export function Screen({ children, scroll = false, style }: PropsWithChildren<{ scroll?: boolean; style?: ViewProps['style'] }>) {
  const content = <View style={[styles.screenContent, style]}>{children}</View>;
  return scroll ? <ScrollView style={styles.screen} contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">{content}</ScrollView> : <View style={styles.screen}>{content}</View>;
}
export function PageHeader({ eyebrow, title, subtitle, right }: { eyebrow?: string; title: string; subtitle?: string; right?: ReactNode }) {
  return <View style={styles.header}><View style={{ flex: 1 }}>{eyebrow ? <Text style={styles.eyebrow}>{eyebrow}</Text> : null}<Text style={styles.title}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{right}</View>;
}
export function Button({ title, onPress, secondary = false, disabled = false, loading = false }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean; loading?: boolean }) {
  return <Pressable accessibilityRole="button" onPress={onPress} disabled={disabled || loading} style={({ pressed }) => [styles.button, secondary && styles.buttonSecondary, pressed && styles.pressed, (disabled || loading) && styles.disabled]}>{loading ? <ActivityIndicator color={secondary ? colors.text : colors.bg} /> : <Text style={[styles.buttonText, secondary && styles.buttonTextSecondary]}>{title}</Text>}</Pressable>;
}
export function Field({ label, ...props }: TextInputProps & { label: string }) {
  return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} style={styles.input} accessibilityLabel={label} {...props} /></View>;
}
export function Card({ children, style }: PropsWithChildren<{ style?: ViewProps['style'] }>) { return <View style={[styles.card, style]}>{children}</View>; }
export function Notice({ children, tone = 'error' }: PropsWithChildren<{ tone?: 'error' | 'success' }>) { return <Text style={[styles.notice, tone === 'success' && styles.noticeSuccess]}>{children}</Text>; }
export const ui = StyleSheet.create({ row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, tag: { color: colors.purple, fontSize: 12, fontWeight: '700', backgroundColor: '#9b8cff1a', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 99, overflow: 'hidden' }, small: { color: colors.muted, fontSize: 12 }, separator: { height: 1, backgroundColor: colors.line, marginVertical: 14 } });
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.bg }, screenContent: { padding: 22, gap: 18 }, scrollContent: { flexGrow: 1, paddingBottom: 36 }, header: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 2 }, eyebrow: { color: colors.purple, fontSize: 11, fontWeight: '800', letterSpacing: 1.6, textTransform: 'uppercase', marginBottom: 8 }, title: { color: colors.text, fontSize: 28, lineHeight: 34, fontWeight: '800', letterSpacing: -0.7 }, subtitle: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 6 }, card: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, borderRadius: 20, padding: 17, gap: 9 }, button: { minHeight: 50, paddingHorizontal: 18, borderRadius: 14, backgroundColor: colors.purple, alignItems: 'center', justifyContent: 'center' }, buttonSecondary: { backgroundColor: colors.cardAlt, borderWidth: 1, borderColor: colors.line }, buttonText: { color: colors.bg, fontWeight: '800', fontSize: 15 }, buttonTextSecondary: { color: colors.text }, pressed: { opacity: 0.82, transform: [{ scale: 0.99 }] }, disabled: { opacity: 0.55 }, field: { gap: 8 }, label: { color: colors.text, fontSize: 13, fontWeight: '700' }, input: { minHeight: 50, paddingHorizontal: 14, paddingVertical: 12, color: colors.text, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.line, borderRadius: 13, fontSize: 15 }, notice: { color: colors.red, fontSize: 13, lineHeight: 19, backgroundColor: '#ff8a971a', borderRadius: 12, padding: 12 }, noticeSuccess: { color: colors.green, backgroundColor: '#73ddb41a' } });
