import { useLocalSearchParams } from 'expo-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, Text, View } from 'react-native';
import { Button, Card, Field, Notice, PageHeader, Screen, colors, ui } from '@/components/ui';
import { api, ApiError, type Currency } from '@/lib/api';
import { useAuth } from '@/providers/auth-provider';
import { formatMoney } from '../(tabs)';
export default function ProjectDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const cache = useQueryClient(); const { user } = useAuth();
  const [message, setMessage] = useState(''); const [milestoneTitle, setMilestoneTitle] = useState(''); const [milestoneAmount, setMilestoneAmount] = useState(''); const [milestoneCurrency, setMilestoneCurrency] = useState<Currency>('USD'); const [error, setError] = useState('');
  const query = useQuery({ queryKey: ['project', id], queryFn: () => api.getProject(id), enabled: !!id, refetchInterval: 20_000 });
  useEffect(() => { if (query.data) void api.markProjectMessagesRead(id); }, [id, query.data]);
  const refresh = () => cache.invalidateQueries({ queryKey: ['project', id] });
  const send = useMutation({ mutationFn: () => api.sendMessage(id, message.trim()), onSuccess: async () => { setMessage(''); await refresh(); }, onError: (e) => setError(e instanceof ApiError ? e.message : 'Message could not be sent.') });
  const status = useMutation({ mutationFn: (value: 'ACTIVE' | 'PAUSED' | 'COMPLETED') => api.updateProjectStatus(id, value), onSuccess: refresh, onError: (e) => setError(e instanceof ApiError ? e.message : 'Status could not be changed.') });
  const addMilestone = useMutation({ mutationFn: () => api.createMilestone(id, { title: milestoneTitle.trim(), amount: milestoneCurrency === 'USD' ? Math.round(Number(milestoneAmount) * 100) : Number(milestoneAmount), currency: milestoneCurrency }), onSuccess: async () => { setMilestoneTitle(''); setMilestoneAmount(''); await refresh(); }, onError: (e) => setError(e instanceof ApiError ? e.message : 'Milestone could not be added.') });
  const updateMilestone = useMutation({ mutationFn: ({ milestoneId, value }: { milestoneId: string; value: string }) => api.updateMilestone(id, milestoneId, { status: value }), onSuccess: refresh, onError: (e) => setError(e instanceof ApiError ? e.message : 'Milestone could not be changed.') });
  if (query.isLoading) return <Screen><Text style={ui.small}>Loading project…</Text></Screen>;
  if (query.isError && !query.data) return <Screen><Card><Text style={{ color: colors.text, fontWeight: '800' }}>Couldn’t load this workspace</Text><Text style={ui.small}>Check your connection or try again.</Text><Button title="Retry" secondary onPress={() => void query.refetch()} /></Card></Screen>;
  const project = query.data; if (!project) return <Screen><Card><Text style={{ color: colors.text, fontWeight: '800' }}>Project not found</Text><Text style={ui.small}>Only project participants can open this workspace.</Text></Card></Screen>;
  const messages = project.conversation?.messages ?? [];
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: colors.bg }} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={88}><Screen scroll><PageHeader eyebrow={project.status.replace('_', ' ')} title={project.job.title} subtitle={`${formatMoney(project.agreedAmount, project.agreedCurrency)} · Shared project workspace`} />{error ? <Notice>{error}</Notice> : null}<Card><Text style={{ color: colors.text, fontWeight: '800' }}>Project status</Text><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{project.status !== 'ACTIVE' && project.status !== 'COMPLETED' && <Button title={project.status === 'PAUSED' ? 'Resume' : 'Start project'} onPress={() => status.mutate('ACTIVE')} loading={status.isPending} />}{project.status === 'ACTIVE' ? <Button title="Pause" secondary onPress={() => status.mutate('PAUSED')} loading={status.isPending} /> : null}{project.status !== 'COMPLETED' ? <Button title="Complete" secondary onPress={() => status.mutate('COMPLETED')} loading={status.isPending} /> : null}</View></Card>
  <Card><Text style={{ color: colors.text, fontWeight: '800', fontSize: 16 }}>Milestones</Text>{project.milestones.length ? project.milestones.map((m) => <View key={m.id} style={{ paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.line, gap: 6 }}><Text style={{ color: colors.text, fontWeight: '700' }}>{m.title}</Text><Text style={ui.small}>{formatMoney(m.amount, m.currency)} · {m.status.replace('_', ' ')}</Text>{m.status === 'PENDING' ? <Pressable onPress={() => updateMilestone.mutate({ milestoneId: m.id, value: 'IN_PROGRESS' })}><Text style={{ color: colors.purple, fontWeight: '700' }}>Start milestone →</Text></Pressable> : m.status === 'IN_PROGRESS' ? <Pressable onPress={() => updateMilestone.mutate({ milestoneId: m.id, value: 'COMPLETED' })}><Text style={{ color: colors.green, fontWeight: '700' }}>Mark complete →</Text></Pressable> : null}</View>) : <Text style={ui.small}>Agree on the next delivery and add your first milestone.</Text>}</Card>
  <Card><Text style={{ color: colors.text, fontWeight: '800' }}>Add a milestone</Text><Field label="Title" value={milestoneTitle} onChangeText={setMilestoneTitle} placeholder="e.g. First design concepts" /><Field label={`Amount (${milestoneCurrency})`} value={milestoneAmount} onChangeText={setMilestoneAmount} keyboardType={milestoneCurrency === 'USD' ? 'decimal-pad' : 'number-pad'} placeholder={milestoneCurrency === 'USD' ? '500.00' : '500000'} /><View style={{ flexDirection: 'row', gap: 8 }}><Button title="USD" secondary={milestoneCurrency !== 'USD'} onPress={() => setMilestoneCurrency('USD')} /><Button title="MMK" secondary={milestoneCurrency !== 'MMK'} onPress={() => setMilestoneCurrency('MMK')} /></View><Button title="Add milestone" onPress={() => addMilestone.mutate()} loading={addMilestone.isPending} disabled={milestoneTitle.trim().length < 2 || !Number(milestoneAmount) || (milestoneCurrency === 'MMK' && !Number.isInteger(Number(milestoneAmount)))} /></Card>
  <Card><Text style={{ color: colors.text, fontSize: 16, fontWeight: '800' }}>Project conversation</Text>{messages.length ? messages.slice(-30).map((m) => <View key={m.id} style={{ alignSelf: m.senderId === user?.id ? 'flex-end' : 'flex-start', maxWidth: '88%', backgroundColor: m.senderId === user?.id ? '#9b8cff24' : colors.cardAlt, borderRadius: 14, padding: 11, marginTop: 8 }}><Text style={{ color: colors.text, lineHeight: 20 }}>{m.body}</Text><Text style={[ui.small, { marginTop: 4 }]}>{m.sender.profile?.name ?? m.sender.email.split('@')[0]}</Text></View>) : <Text style={ui.small}>No messages yet. Say hello and agree on the next step.</Text>}</Card></Screen><View style={{ flexDirection: 'row', gap: 8, paddingHorizontal: 14, paddingVertical: 10, borderTopColor: colors.line, borderTopWidth: 1, backgroundColor: colors.bg }}><TextInputShim value={message} onChangeText={setMessage} /><Button title="Send" onPress={() => send.mutate()} loading={send.isPending} disabled={!message.trim()} /></View></KeyboardAvoidingView>;
}
function TextInputShim({ value, onChangeText }: { value: string; onChangeText: (s: string) => void }) { return <Field label="Message" value={value} onChangeText={onChangeText} placeholder="Write a message…" style={{ flex: 1 }} />; }
