import { useRouter } from 'expo-router';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Text, View } from 'react-native';
import { Button, Field, Notice, PageHeader, Screen, colors, ui } from '@/components/ui';
import { api, ApiError, type Currency } from '@/lib/api';
export default function NewJobScreen() {
  const router = useRouter(); const cache = useQueryClient();
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState(''); const [budget, setBudget] = useState(''); const [currency, setCurrency] = useState<Currency>('USD'); const [deadline, setDeadline] = useState(''); const [draftId, setDraftId] = useState<string | null>(null); const [error, setError] = useState('');
  const deadlineValid = !deadline || (/^\d{4}-\d{2}-\d{2}$/.test(deadline) && !Number.isNaN(Date.parse(`${deadline}T00:00:00Z`)));
  const create = useMutation({ mutationFn: async () => { const jobId = draftId ?? (await api.createJob({ title: title.trim(), description: description.trim(), category: category.trim() || undefined, budgetAmount: currency === 'USD' ? Math.round(Number(budget) * 100) : Math.round(Number(budget)), budgetCurrency: currency, deadline: deadline ? new Date(`${deadline}T00:00:00Z`).toISOString() : undefined })).id; try { return await api.publishJob(jobId); } catch (e) { setDraftId(jobId); throw e; } }, onSuccess: async (job) => { await cache.invalidateQueries({ queryKey: ['jobs'] }); router.replace({ pathname: '/jobs/[id]', params: { id: job.id } }); }, onError: (e) => setError(e instanceof ApiError ? e.message : 'Could not publish your project. Please try again.') });
  return <Screen scroll><PageHeader eyebrow="Client workspace" title="Write a clear brief." subtitle="Share what you need, what success looks like, and your budget." /><Field label="Project title" value={title} onChangeText={setTitle} placeholder="e.g. Design a welcoming bakery website" /><Field label="Description" value={description} onChangeText={setDescription} multiline numberOfLines={7} textAlignVertical="top" placeholder="Share the context, outcome, and what success looks like…" style={{ minHeight: 160 }} /><Field label="Category · optional" value={category} onChangeText={setCategory} placeholder="e.g. Product design" /><Text style={{ color: colors.text, fontWeight: '800' }}>Budget currency</Text><View style={{ flexDirection: 'row', gap: 8 }}><Button title="USD" secondary={currency !== 'USD'} onPress={() => setCurrency('USD')} /><Button title="MMK" secondary={currency !== 'MMK'} onPress={() => setCurrency('MMK')} /></View><Field label={currency === 'USD' ? 'Budget (USD)' : 'Budget (whole MMK)'} value={budget} onChangeText={setBudget} keyboardType={currency === 'USD' ? 'decimal-pad' : 'number-pad'} placeholder={currency === 'USD' ? '1500.00' : '1500000'} /><Field label="Target deadline · optional (YYYY-MM-DD)" value={deadline} onChangeText={setDeadline} placeholder="2026-12-31" />{deadline && !deadlineValid ? <Text style={{ color: colors.red, fontSize: 12 }}>Enter a valid date as YYYY-MM-DD.</Text> : null}{error ? <Notice>{error}</Notice> : null}<Button title="Publish project" onPress={() => create.mutate()} loading={create.isPending} disabled={title.trim().length < 5 || description.trim().length < 20 || !Number(budget) || Number(budget) <= 0 || (currency === 'MMK' && !Number.isInteger(Number(budget))) || !deadlineValid} /><Text style={ui.small}>Publishing makes your brief visible to freelancers. No payment is processed.</Text></Screen>;
}
