import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Text, View } from 'react-native';
import { Button, Card, Field, Notice, PageHeader, Screen, colors, ui } from '@/components/ui';
import { api, ApiError, type Currency } from '@/lib/api';

export default function NewProposalScreen() {
  const { jobId, title, budgetAmount, budgetCurrency } = useLocalSearchParams<{ jobId: string; title: string; budgetAmount: string; budgetCurrency: Currency }>();
  const router = useRouter(); const cache = useQueryClient();
  const [coverLetter, setCoverLetter] = useState(''); const [bid, setBid] = useState(''); const [currency, setCurrency] = useState<Currency>(budgetCurrency ?? 'USD'); const [days, setDays] = useState(''); const [error, setError] = useState('');
  const mutation = useMutation({ mutationFn: () => api.createProposal({ jobId, coverLetter: coverLetter.trim(), bidAmount: currency === 'USD' ? Math.round(Number(bid) * 100) : Math.round(Number(bid)), bidCurrency: currency, estimatedDays: days ? Number(days) : undefined }), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ['proposals'] }); router.replace('/(tabs)/proposals'); }, onError: (e) => setError(e instanceof ApiError ? e.message : 'Could not send your proposal. Please try again.') });
  return <Screen scroll><PageHeader eyebrow="Your proposal" title="Make your case." subtitle={`Send a thoughtful proposal for ${title ?? 'this project'}.`} /><Card><Text style={ui.small}>Client budget</Text><Text style={{ color: colors.text, fontWeight: '800', fontSize: 20 }}>{budgetCurrency === 'USD' ? `USD $${(Number(budgetAmount ?? 0) / 100).toFixed(2)}` : `${Number(budgetAmount ?? 0).toLocaleString()} MMK`}</Text></Card><Field label="Cover letter" value={coverLetter} onChangeText={setCoverLetter} multiline numberOfLines={6} textAlignVertical="top" placeholder="What outcome can you create, and how would you approach the work?" style={{ minHeight: 150 }} /><Text style={ui.small}>Share your approach and what you need to get started. (20 character minimum)</Text><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: '700', marginBottom: 8 }}>Currency</Text><View style={{ flexDirection: 'row', gap: 8 }}><Button title="USD" secondary={currency !== 'USD'} onPress={() => setCurrency('USD')} /><Button title="MMK" secondary={currency !== 'MMK'} onPress={() => setCurrency('MMK')} /></View></View></View><Field label={`Your bid (${currency})`} value={bid} onChangeText={setBid} keyboardType={currency === 'USD' ? 'decimal-pad' : 'number-pad'} placeholder={currency === 'USD' ? '1500.00' : '1500000'} /><Field label="Estimated delivery (days) · optional" value={days} onChangeText={setDays} keyboardType="number-pad" placeholder="14" />{error ? <Notice>{error}</Notice> : null}<Button title="Send proposal" onPress={() => mutation.mutate()} loading={mutation.isPending} disabled={coverLetter.trim().length < 20 || !Number(bid) || Number(bid) <= 0 || (currency === 'MMK' && !Number.isInteger(Number(bid))) || (!!days && !Number(days))} /><Text style={ui.small}>No payment is processed when you submit. This records your proposal terms for the client.</Text></Screen>;
}
